"""Per-user category taxonomy — generated by LLM from your real sessions.

Why dynamic?
  An engineer's AI usage and a creator's AI usage look totally different. A fixed
  10-category taxonomy mismatches both. Instead, on first run we sample your
  sessions and let an LLM induce categories that fit YOUR specific patterns.

Storage:
  ~/.tokenpayback/taxonomy.yaml  ← user-editable. Comments preserved.

Lifecycle:
  - First `tokenpayback` run with no taxonomy → discover & save
  - Subsequent runs → load existing
  - `tokenpayback taxonomy regen` → re-discover from scratch
  - User can edit the yaml at any time (rename, change baselines, add categories)
"""
from __future__ import annotations
import json
import os
import random
import sys
from pathlib import Path

import yaml

DATA_DIR = Path.home() / ".tokenpayback"
TAXONOMY_PATH = DATA_DIR / "taxonomy.yaml"
SAMPLE_SIZE = 24  # how many sessions to show the LLM during discovery


DEFAULT_TAXONOMY = {
    "categories": [
        {"id": "code-shipped", "icon": "🚢", "label": "Code shipped",
         "description": "Building or completing a feature, committed to repo",
         "baseline_usd": 60, "per_pr_usd": 600, "per_line_usd": 0.30},
        {"id": "bug-fixed", "icon": "🐛", "label": "Bug fixed",
         "description": "Diagnosed and fixed a defect, with verification",
         "baseline_usd": 80, "per_pr_usd": 700, "per_line_usd": 0.40},
        {"id": "infra-changed", "icon": "⚙️", "label": "Infra changed",
         "description": "Deploy/CI/config/install/auth — system state change",
         "baseline_usd": 50, "per_pr_usd": 200, "per_line_usd": 0.10},
        {"id": "info-gathered", "icon": "📚", "label": "Info gathered",
         "description": "Research, docs, market scan, competitive analysis",
         "baseline_usd": 25, "per_pr_usd": 0, "per_line_usd": 0.05},
        {"id": "ideas-explored", "icon": "💡", "label": "Ideas explored",
         "description": "Brainstorm, strategy, product thinking",
         "baseline_usd": 20, "per_pr_usd": 0, "per_line_usd": 0},
        {"id": "life-shipped", "icon": "🎯", "label": "Life shipped",
         "description": "Personal tasks: documents, videos, organizing, lookups",
         "baseline_usd": 30, "per_pr_usd": 0, "per_line_usd": 0.20},
        {"id": "question-answered", "icon": "❓", "label": "Question answered",
         "description": "Quick Q&A, lookup, status check",
         "baseline_usd": 5, "per_pr_usd": 0, "per_line_usd": 0},
    ],
    "discovered": False,
    "rationale": "Built-in fallback taxonomy. Run `tokenpayback taxonomy regen` to personalize.",
}


DISCOVERY_SYSTEM = """You analyze how ONE specific person uses AI coding agents (Claude Code, Codex, Hermes, etc.).
Given a sample of their recent sessions, your job is to INDUCE 6–9 categories that fit how THIS person actually uses AI.

Rules:
- Be SPECIFIC to patterns you see, not generic. If they edit videos, "TikTok video editing" is a real category.
  If they review CRM data, "sales-ops research" beats "research".
- Cover at least 2 sessions per category from the sample (otherwise drop it).
- Pick an icon (emoji) that captures the activity vividly.
- Estimate a baseline_usd: what would a typical session in this category be worth to this person? (Use the cost
  of the sessions you see as a hint, but VALUE > COST in most cases — even cheap sessions can be high-value.)
- description should be 1 sentence the classifier will later use to match new sessions.
- rationale should be 1-2 sentences explaining how the categories fit this user.

Return JSON exactly:
{
  "categories": [
    {
      "id": "kebab-case-slug",
      "icon": "🚢",
      "label": "Short Label",
      "description": "When to use this category, 1 sentence.",
      "baseline_usd": 40,
      "per_pr_usd": 0,
      "per_line_usd": 0
    },
    ...
  ],
  "rationale": "..."
}

For code categories ONLY, set per_pr_usd and per_line_usd to non-zero. Otherwise zero them out.
"""


def _llm_chat(messages: list[dict], max_tokens: int = 2000) -> str:
    """Provider-agnostic chat call. Reuses classify_sessions._detect_provider."""
    from .classify_sessions import _detect_provider, _classify_anthropic, _classify_openai_compatible
    provider, base_url, api_key, model = _detect_provider()
    # We need raw text here, not dict — reach down to the lower-level call
    import requests
    if provider == "anthropic":
        resp = requests.post(
            f"{base_url}/messages",
            headers={"x-api-key": api_key, "anthropic-version": "2023-06-01", "Content-Type": "application/json"},
            json={
                "model": model, "max_tokens": max_tokens,
                "system": messages[0]["content"] if messages[0]["role"] == "system" else "",
                "messages": [m for m in messages if m["role"] != "system"],
            }, timeout=120,
        )
        resp.raise_for_status()
        return resp.json()["content"][0]["text"]
    payload = {"model": model, "messages": messages, "max_tokens": max_tokens}
    if "gpt-5" not in model and "o1" not in model and "o3" not in model:
        payload["temperature"] = 0.3
        payload["response_format"] = {"type": "json_object"}
    resp = requests.post(
        f"{base_url}/chat/completions",
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        json=payload, timeout=120,
    )
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"]


def _extract_json(text: str) -> dict:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        s, e = text.find("{"), text.rfind("}")
        if s >= 0 and e > s:
            return json.loads(text[s : e + 1])
        raise


def _sample_for_discovery(sessions: list[dict], k: int = SAMPLE_SIZE) -> list[dict]:
    """Pick a representative sample: spread across agents + cost magnitudes."""
    if len(sessions) <= k:
        return sessions
    by_agent: dict[str, list[dict]] = {}
    for s in sessions:
        by_agent.setdefault(s.get("agent", "unknown"), []).append(s)
    chosen: list[dict] = []
    while len(chosen) < k:
        added = False
        for agent_sessions in by_agent.values():
            if not agent_sessions:
                continue
            chosen.append(agent_sessions.pop(0))
            added = True
            if len(chosen) >= k:
                break
        if not added:
            break
    return chosen


def discover_taxonomy(sessions: list[dict]) -> dict:
    """Use the LLM to induce categories from a sample of real sessions."""
    if not sessions:
        return DEFAULT_TAXONOMY
    sample = _sample_for_discovery(sessions)
    digest_items = []
    for s in sample:
        digest_items.append({
            "agent": s.get("agent"),
            "project": s.get("project", "")[:60],
            "first_prompt": (s.get("first_prompt") or "")[:240],
            "tools": s.get("tool_counts"),
            "files_touched_sample": (s.get("files_touched") or [])[:5],
            "bash_sample": (s.get("bash_sample") or [])[:3],
            "est_cost_usd": s.get("est_cost_usd"),
        })
    user_msg = (
        f"Here are {len(digest_items)} recent sessions from this user "
        f"(across {len({d['agent'] for d in digest_items})} agents). "
        "Induce categories that describe how THIS person uses AI.\n\n"
        f"```json\n{json.dumps(digest_items, ensure_ascii=False, indent=2)[:30000]}\n```"
    )
    print(f"[taxonomy] discovering from {len(sample)} sample sessions...", file=sys.stderr)
    text = _llm_chat([
        {"role": "system", "content": DISCOVERY_SYSTEM},
        {"role": "user", "content": user_msg},
    ], max_tokens=2500)
    result = _extract_json(text)
    cats = result.get("categories") or []
    if not cats:
        print("[taxonomy] ! LLM returned no categories, falling back to default", file=sys.stderr)
        return DEFAULT_TAXONOMY
    out = {"categories": cats, "discovered": True, "rationale": result.get("rationale", "")}
    print(f"[taxonomy] discovered {len(cats)} categories:", file=sys.stderr)
    for c in cats:
        print(f"  {c.get('icon','•')}  {c.get('label','?'):<25} — {c.get('description','')[:80]}", file=sys.stderr)
    return out


def save_taxonomy(taxonomy: dict, path: Path = TAXONOMY_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "# Your personal AI activity taxonomy — generated from your real sessions.\n"
        "# Edit freely: rename categories, change baselines, add new ones.\n"
        "# Re-discover with: tokenpayback taxonomy regen\n\n"
    )
    body += yaml.safe_dump(taxonomy, allow_unicode=True, sort_keys=False)
    path.write_text(body, encoding="utf-8")


def load_taxonomy(path: Path = TAXONOMY_PATH) -> dict:
    if not path.exists():
        return DEFAULT_TAXONOMY
    try:
        return yaml.safe_load(path.read_text(encoding="utf-8")) or DEFAULT_TAXONOMY
    except Exception as e:
        print(f"[taxonomy] ! failed to load {path}: {e}", file=sys.stderr)
        return DEFAULT_TAXONOMY


def ensure_taxonomy(sessions: list[dict], *, force_regen: bool = False, path: Path = TAXONOMY_PATH) -> dict:
    """Discover + save if no taxonomy yet (or force_regen). Otherwise load."""
    if not force_regen and path.exists():
        return load_taxonomy(path)
    if not sessions:
        return DEFAULT_TAXONOMY
    taxo = discover_taxonomy(sessions)
    save_taxonomy(taxo, path)
    return taxo


def category_index(taxonomy: dict) -> dict:
    """Return dict {category_id → category_dict} for fast lookup."""
    return {c["id"]: c for c in (taxonomy.get("categories") or [])}
